### ISSUE TITLE
xliff-tasks should publish to BAR

### ISSUE THREAD

**Issue by crummel** [dotnet/xliff-tasks#114]
Source-build uses the Build Asset Registry to determine what versions of each repo to build.  [CoreFX](https://github.com/dotnet/corefx/blob/4a4b2cfd556feaa1c112afc604217d5c628385a2/eng/pipelines/publish.yml) has an example of how to publish BAR packages with Arcade.  Please contact @crummel with any questions.

**Comment by tmeschter** [comment]
@crummel We are setting the bit that purports to turn on BAR publishing in Azure:

https://github.com/dotnet/xliff-tasks/blob/master/eng/azure-pipelines.yml#L23

It's not clear to me if something else is needed.

**Comment by crummel** [comment]
It looks like no channels are being published to, which means it can't be taken up:
```
dotnet Microsoft.DotNet.Darc.dll get-default-channels --source-repo https://github.com/dotnet/xliff-tasks
No matching channels were found.
```
Do you want to add it or should I?  Would you say it's more accurate to put the Xliff master branch under ".NET Tools" or ".NET Core 3 Dev"?

**Comment by nguerrera** [comment]
.NET Tools sounds more accurate. What is the impact of that?

**Comment by nguerrera** [comment]
@crummel Go ahead and add it, I'd say...

**Comment by crummel** [comment]
People will be able to subscribe to xliff-tasks using that channel and get automatic updates each time you publish.  It shouldn't really affect things on the Xliff side.  I've added the channel, thanks!
