### ISSUE TITLE
Avoid coupling of Xliff with source generator for EmbeddedResources

### ISSUE THREAD

**Issue by tmat** [dotnet/xliff-tasks#19]
Source generator for EmbeddedResources is a general purpose feature that can be included in dotnet SDK, while xliff supports very specific localization process. These two features should be completely orthogonal.

https://github.com/dotnet/cli/pull/6800/commits/dfc03e7f2c38c553791d63f62efa1c965922c1cb#diff-d5472e2c31596b45aba8b82e71316606R42

**Comment by garath** [comment]
This repository has moved to "maintenance only" mode, though it remains important to .NET efforts. We're closing stale issues. Please feel free to reopen if desired and we'll triage the issue.
