### ISSUE TITLE
Better support for resx files with the same name in different folders

### ISSUE THREAD

**Issue by nguerrera** [dotnet/xliff-tasks#206]
If a project has two resx files with the same name, xliff tasks will fail with:

https://github.com/dotnet/xliff-tasks/blob/91ec2447aac60ff9992f61f061de571f01ad2a34/src/XliffTasks/Tasks/GatherXlf.cs#L66-L68

However, doing munges with the resource names that will be picked, so you need more than just set XlfTranslatedFilename.

Here is how dotnet/cli handled this, using custom Namespace metadata that then flows to ManifestResourceName and XlfTranslatedFilename:

https://github.com/dotnet/cli/blob/b8fd3deb8714db9d1a7c8af6a6639930a9368595/build/GenerateResxSource.targets#L17-L29

A portion of this was moved into arcade, and the collision between these two custom targets caused CLI to lose localization in 3.0 due to incorrectly chosen resource names.

xliff-tasks should just handle resx files in different folders correctly and not put the burden of this customization on arcade or other consumers.

**Comment by garath** [comment]
This repository has moved to "maintenance only" mode, though it remains important to .NET efforts. We're closing stale issues. Please feel free to reopen if desired and we'll triage the issue.
