### ISSUE TITLE
Build fails after a clean

### ISSUE THREAD

**Issue by wachaudh** [dotnet/xliff-tasks#342]
My build fails with the following error after I clean a project:

```
error : 'xlf/Resources.cs.xlf' is out-of-date with 'Resources.resx'. Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBuild=true to update them on every build, but note that it is strongly discouraged to set UpdateXlfOnBuild=true in official/CI build environments as they should not modify source code during the build. 
```

xlf/Resources.cs.xlf and Resources.resx have the same strings and are not out of date. I have attached an example project which demonstrates the issue.

**Steps to reproduce the error**

Call the UpdateXlf target to generate the xlf files:
```
msbuild localizedStrings/localizedStrings.csproj /restore /t:UpdateXlf
```
Build the project, works fine as expected:
```
msbuild localizedStrings/localizedStrings.csproj /t:Build
```
Clean the project and build again. 
```
msbuild localizedStrings/localizedStrings.csproj /t:Clean,Build
```

The last step fails with the aforementioned error. Nothing changed about xlf/Resources.cs.xlf and Resources.resx so I shouldn't be getting an error.
[localizedStrings.zip](https://github.com/dotnet/xliff-tasks/files/4356981/localizedStrings.zip)

**Comment by brendanzagaeski** [comment]
**Workaround**

As Waleed and I were experimenting with this a bit more, we noticed that the error no longer happens if we remove the empty `<comment></comment>` element from the *.resx* file:

```diff
@@ -15,8 +15,6 @@
     
    <data name="test" xml:space="preserve">
         <value>Testing</value>
-        <comment>
-        </comment>
     </data>
 
 </root>
```

**Comment by garath** [comment]
This repository has moved to "maintenance only" mode, though it remains important to .NET efforts. We're closing stale issues. Please feel free to reopen if desired and we'll triage the issue.
