### ISSUE TITLE
Intermittent error in F#: The target "UpdateXlf" does not exist in the project

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/xliff-tasks#350]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

@brettfo reported that F# builds are ocassionally failing with this error message ([Sample build](https://dev.azure.com/dnceng/public/_build/results?buildId=481130&view=logs&j=30a648ac-36f5-5545-42a5-c22d8a066086&t=e7cd1004-488a-5524-c810-01005c1d795b)): 

```
##[error]src\fsharp\fsi\fsi.fsproj(0,0): error MSB4057: (NETCORE_ENGINEERING_TELEMETRY=Build) The target "UpdateXlf" does not exist in the project.
```

Interestingly, when the job is retried it succeeds. @brettfo thinks this might be a problem downloading the Xliff nupkg.

**Comment by garath** [comment]
Transferring to xliff as this appears to be an issue with the xliff target or nuget package.

**Comment by garath** [comment]
This repository has moved to "maintenance only" mode, though it remains important to .NET efforts. We're closing stale issues. Please feel free to reopen if desired and we'll triage the issue.

**Comment by AraHaan** [comment]
I am facing this issue when building the tip of the main branch of Roslyn and so now the resx files claim to be invalid and cause over 3.4k compile errors.
