### ISSUE TITLE
Avoid running in design-time builds / LUT background builds

### ISSUE THREAD

**Issue by nguerrera** [dotnet/xliff-tasks#36]
Right now, UpdateXlfOnBuild hooks on to BeforeBuild without conditions, but we should make sure we only do the updating when a normal build is in progress.

**Comment by KevinH-MS** [comment]
For LUT, you can check ```'$(BuildingForLiveUnitTesting)' == 'true'```

**Comment by tmeschter** [comment]
For design-time builds in SDK-based projects, we need to check the `$(DesignTimeBuild)` property.
For design-time builds in csproj-based projects, we need to check the `$(BuildingProject)` property (which is `false` for design-time builds).

**Comment by davkean** [comment]
I've ran into situation where runs in design-time builds but cannot figure out repro. It breaks the build and therefore turns of semantic errors in Roslyn. Failing turning it off - it would be great if the targets respected ContinueOnError="$(ContinueOnError)" which is set for design-time builds.
