### ISSUE TITLE
Official build seems broken since 2020/9/1, 404 when trying to use a MyGet feed

### ISSUE THREAD

**Issue by dagood** [dotnet/xliff-tasks#368]
https://dev.azure.com/dnceng/internal/_build?definitionId=485&branchName=master

Example:

> D:\a\1\s\.dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(130,5): error : Unable to load the service index for source https://vside.myget.org/F/vssdk/api/v3/index.json. [D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20478.3\tools\SdkTasks\PublishBuildAssets.proj]
> D:\a\1\s\.dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(130,5): error :   Response status code does not indicate success: 404 (Feed does not exist.). [D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20478.3\tools\SdkTasks\PublishBuildAssets.proj]
> ##[error].dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(130,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) Unable to load the service index for source https://vside.myget.org/F/vssdk/api/v3/index.json.

@dotnet/dnceng (repo maintainers)

**Comment by dagood** [comment]
The timing corresponds to Arcade SDK auto-updates getting unblocked: https://github.com/dotnet/xliff-tasks/pull/352

**Comment by lukas-lansky** [comment]
Let me check.

**Comment by lukas-lansky** [comment]
@riarenas @garath Any idea what might have gone wrong here?

**Comment by riarenas** [comment]
The error message seems pretty clear. That feed doesn't exist.

This repo has a bunch of myget feeds in its versions.props, which should all be removed, and we should find a source for any packages that are then not found.

https://github.com/dotnet/xliff-tasks/blob/5e705934054178cdbe546b18ae94646ef3fbca12/eng/Versions.props#L27-L37

**Comment by riarenas** [comment]
Well, looks like it's the best case scenario. Just removing those restoreSources fixes the issue.

https://dnceng.visualstudio.com/internal/_build/results?buildId=839791&view=results
