### ISSUE TITLE
Evaluate choice in package IDs

### ISSUE THREAD

**Issue by AArnott** [dotnet/xliff-tasks#412]
All Microsoft internal tools packages should have IDs that begin with `Microsoft.` so that their absence from nuget.org does not present a dependency confusion vulnerability to repos that consume it from one feed and also consume nuget.org via nuget.config.

**Comment by AArnott** [comment]
@jonfortescue, I hear you're the one to look at this.

**Comment by jonfortescue** [comment]
This is not actually related to my epic. Kicking back to triage.

**Comment by jakubstilec** [comment]
[Async Triage]: @AArnott please could you add description to have more context?

**Comment by AArnott** [comment]
The description was blank before to avoid disclosing a vulnerability before it was announced. I filled it in now.

**Comment by riarenas** [comment]
FYI @mmitche for guidance

**Comment by mmitche** [comment]
Yes, we should make this the prefix.

**Comment by riarenas** [comment]
@markwilkie @Chrisboh @tkapin How do we want to handle these kinds of changes in Xliff-tasks? It's not a giant change so I'm leaning towards throwing this in FR, it requires changing the package name and then making sure arcade depends on the new name.

**Comment by markwilkie** [comment]
Seems to me this is something we should do from a compliance perspective - so ya, FR.  @ilyas1974 ?

**Comment by ilyas1974** [comment]
I agree. Seems like something that we can take care of in FR.

**Comment by ilyas1974** [comment]
@jonfortescue what is the status of this?

**Comment by jonfortescue** [comment]
@ilyas1974 this was meant to be handed off to the next person on FR but I was absent the day of hand-off; sorry about that. A PR is in (https://github.com/dotnet/xliff-tasks/issues/478) but I'm worried about the consequences changing the name will have.

**Comment by lpatalas** [comment]
I'm currently on FR and I will take over this issue from Jon.

**Comment by riarenas** [comment]
I don't think the name change is too concerning. For the most part, repos get xliff from arcade, so we will need to make sure arcade still gets updated with the new package version.

I think all we wound need is:

*  change https://github.com/dotnet/arcade/blob/dc5deb120047922d85aa0a002e1aea64f2db41b2/eng/Version.Details.xml#L71 to use the new name
* change https://github.com/dotnet/arcade/blob/dc5deb120047922d85aa0a002e1aea64f2db41b2/eng/Versions.props#L81 and everything that uses that property
* Let partners know that the package name has changed in case they have custom references to the package.

**Comment by lpatalas** [comment]
Thanks for the tips @riarenas. I double checked @jonfortescue's changes and they seem ok. Build and tests finish successfully. I'm not sure if I can do any more due diligence there so I think we just need to merge it and see if the package is published correctly.

Is there someone specific I should put as a reviewer? Currently I've added @riarenas and @MattGal.

**Comment by lpatalas** [comment]
Based on @mmitche suggestion I renamed the package to `Microsoft.DotNet.XliffTasks`. I've already updated the PR https://github.com/dotnet/xliff-tasks/pull/478. After it's merged we need to make changes in Arcade that @riarenas described above.

**Comment by premun** [comment]
I see this package is used in 6 repos, I will open a PR in each so that people know about the name change:
- `roslyn-tools`
- `arcade`
- `sdk`
- `upgrade-assistant`
- `machinelearning`

**Comment by jonfortescue** [comment]
@premun Just so you know, the package is used in dozens of repos that pull it in through arcade. All of the repos in [this issue](https://github.com/dotnet/core-eng/issues/12670), for example, use xliff-tasks.

**Comment by riarenas** [comment]
If they bring it through arcade they shouldn't need any changes beyond having arcade use the new name.

**Comment by greenEkatherine** [comment]
PR merged, is there anything else to do?

**Comment by AArnott** [comment]
Looks good to me. Thank you.

**Comment by ilyas1974** [comment]
Closing issue - if anything else is needed, please let us know and we will address it.
