### ISSUE TITLE
Warn when placeholder counts vary

### ISSUE THREAD

**Issue by tmeschter** [dotnet/xliff-tasks#52]
We should warn when the number of placeholders in a localized string resource from a .resx file is greater than the number of placeholders in the string in the original string. Attempting to format using the localized string is likely to fail because there is no corresponding argument to `string.Format`, leading to an exception at run time.

This can happen if we already have a translation for a string such as `"{0} Alpha {1}"`, but it is later changed to have fewer placeholders, e.g. `"Alpha {0}"`. Until the next localization pass updates the .xlf files, the localized versions will still have two placeholders.

I imagine we would just have the MSBuild task check for this and log a warning. We may want to scope it to just .resx files.

**Comment by nguerrera** [comment]
Should we revert the translated text to English instead of (or in addition to) warning?

**Comment by tmeschter** [comment]
Upon further reflection, I think we should revert the translated text to English instead of issuing a warning.

If we issue a warning, the only option available to the developer is to revert the text manually--or add a new resource with a new name and use that instead, which is effectively the same thing. So we might as well just go ahead and revert the text automatically.

And if the number of placeholders has changed the text is probably so different that the existing translations are no longer of any value--we're not losing anything by reverting them.

**Comment by japj** [comment]
I think MAT will also change the state if the source of translated item changes (to trigger translator action), so that will probably also be needed when you detect this issue.

**Comment by tmeschter** [comment]
@japj XliffTasks already handles that. Changing the original resource will update the state from "translated" to "needs-review-translation" on the next build.

**Comment by davkean** [comment]
Here's another example: https://github.com/dotnet/project-system/pull/3775. This string actually fails to parse.

**Comment by nguerrera** [comment]
That one looks to be translator error, but indeed we could have caught this with diagnostic for mismatched placeholders

**Comment by nguerrera** [comment]
Or if we silently reverted to English, we’d spot it when hand back was flagged as not up to date and a subsequent update to English would show up in a commit to get the PR green and we’d see the problem there too.
