### ISSUE TITLE
Localize .vsct file is not working

### ISSUE THREAD

**Issue by chagong** [dotnet/xliff-tasks#582]
I am trying to localize my vsix project which is a Visual Studio extension. I added a menu item in vsct file and I want to localize the text of this menu item, and I translated the button text of the menu item:
![image](https://user-images.githubusercontent.com/831821/163789851-55dd632f-e370-4859-aaad-56d76df9d889.png)

However when running it it doesn't show the translated text:
![image](https://user-images.githubusercontent.com/831821/163789319-3fbdae07-71c4-443b-8c1c-1a5288afea3f.png)

But the localization for .resx file is working:
![image](https://user-images.githubusercontent.com/831821/163790032-2a413a90-293a-41bf-83b6-5a33a70e5226.png)
![image](https://user-images.githubusercontent.com/831821/163790122-8ff6e399-b506-49cb-8415-c5ce8a13ef83.png)

Seems like the generated vsct is not built into resources.dll. Am I missing any configuration for vsct? Or can you share an example of using xlifftasks for vsct localization?

Thanks!

**Comment by chagong** [comment]
@dotnet/dnceng

**Comment by ilyas1974** [comment]
@jonfortescue , is this something you can help with?

**Comment by chagong** [comment]
And I do it with Visual Studio 2022.

**Comment by chagong** [comment]
Yeah, we don't plan to use Arcade (kind of heavy).  Here is csproj
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MinimumVisualStudioVersion>17.0</MinimumVisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectTypeGuids>{82b43b9b-a64c-4715-b499-d71e9ca2bd60};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <ProjectGuid>{A4B9F962-EA8E-4261-8A3D-949DA097EC87}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>XlfTest</RootNamespace>
    <AssemblyName>XlfTest</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>true</CopyOutputSymbolsToOutputDirectory>
    <StartAction>Program</StartAction>
    <StartProgram Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)devenv.exe</StartProgram>
    <StartArguments>/rootsuffix Exp</StartArguments>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Command1.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="XlfTestPackage.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Design" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.0.31902.203" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="17.1.4057" />
    <PackageReference Include="XliffTasks">
      <Version>1.0.0-beta.21374.1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="xlf\*.xlf" />
    <None Include="Properties\xlf\*.xlf" />
  </ItemGroup>
  <ItemGroup>
    <VSCTCompile Include="XlfTestPackage.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Command1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="'$(VSToolsPath)' != ''" />
  
  <Target Name="AssignEnCultureToNeutralCto" BeforeTargets="MergeCtoResource">
    <ItemGroup>
      <_GeneratedCTOFilesWithCulture Include="@(_GeneratedCTOFilesWithNoCulture)">
        <Culture>en</Culture>
        <WithCulture>true</WithCulture>
      </_GeneratedCTOFilesWithCulture>
      <_GeneratedCTOFilesWithNoCulture Remove="@(_GeneratedCTOFilesWithNoCulture)" />
      <_ResourcesToMergeWithCTOWithCultureMetadata Condition="'%(WithCulture)' != 'true'">
        <Culture>en</Culture>
        <WithCulture>true</WithCulture>
      </_ResourcesToMergeWithCTOWithCultureMetadata>
    </ItemGroup>
  </Target>
</Project>

**Comment by chagong** [comment]
> @chagong Could you show me what project properties you're setting here? I know razor-tooling is localizing with vscts ([here](https://github.com/dotnet/razor-tooling/tree/main/src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf)) but they're on arcade so their configuration is the default.

And I just checked razor-tooling project, they have 2 vsct, one is empty and another one haven't been translated.

**Comment by jonfortescue** [comment]
Hmm, indeed those aren't translated...that's strange and I'll have to follow up on that. In any case, [these](https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hans.xlf) vscts in roslyn are getting translations. 

I've been digging through their code to try to find something they're doing differently than you but I haven't come up with anything yet. Will keep you in the loop.

**Comment by ilyas1974** [comment]
@jonfortescue , can you update this issue with current status please?

**Comment by jonfortescue** [comment]
Did some digging with @chagong offline and determined that this is _not_ a problem with xliff-tasks, per se, as we found one project where this functionality worked. We diffed that project and his, but resolving these differences did not resolve the issue. Reached out to @tmeschter and @nguerrera for more help and had some help digging through a binlog, but still no resolution yet.

**Comment by jonfortescue** [comment]
Issue resolved offline. The issue was with VSSDK reinsertion and a few extra properties/targets had to be set. See below for solution:

![image](https://user-images.githubusercontent.com/13228069/168132748-73b5603a-a73c-4275-9330-b6788e7457a4.png)
