### ISSUE TITLE
.vsct has no equivalent of the <notes> element in .resx

### ISSUE THREAD

**Issue by genlu** [dotnet/xliff-tasks#61]
.vsct has no equivalent of the <notes> element in .resx, which makes it hard to provide the context for LOC team to translate the text.

**Comment by nguerrera** [comment]
One thing that does work is to add the notes to the xlf file manually. xliff-tasks knows that vsct files can't have notes, so it will not try to delete them. The problem there, though, is that you have to do it 13 times. :(

I guess we could pick some schema for storing the notes in the .vsct file itself, but we'd have to make sure we won't break VS by putting custom notes in that file. 

We could also create a sidecar .notes.xml file or something.

**Comment by garath** [comment]
This repository has moved to "maintenance only" mode, though it remains important to .NET efforts. We're closing stale issues. Please feel free to reopen if desired and we'll triage the issue.
