### ISSUE TITLE
Allow opting out individual files, or don't produce xlf file if no translatable elements exist

### ISSUE THREAD

**Issue by davidwengier** [dotnet/xliff-tasks#64]
I have a XamlRule file in a project where Xlf translations are turned on (and desired) but when an individual file has no translatable attributes (eg: https://github.com/davidwengier/project-system/blob/SplitFileAndBrowseObjectNodes/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/None.xaml) we still get a dozen or so basically empty xlf files generated

https://github.com/davidwengier/project-system/blob/SplitFileAndBrowseObjectNodes/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/None.xaml.fr.xlf

It would be ideal to prevent this in some way, presumably either via some metadata that can opt out a file in the project file, or simply by not creating an xlf file, or attempting to update same, until there is something to write.

**Comment by tmeschter** [comment]
@davidwengier Both approaches would be valuable.

xliff-tasks aside, I _think_ .resx files already have an attribute that specifies that translation should be skipped. We should consider honoring that and adopting it for the other file types as well.

**Comment by nguerrera** [comment]
> presumably either via some metadata that can opt out a file in the project file

You can opt out files already using XlfInput="false" metadata.

**Comment by davidwengier** [comment]
XlfInput works great

**Comment by tmeschter** [comment]
@davidwengier I realize this has been closed for a couple of months, but could you update the README.md to document the XlfInput metadata?

**Comment by davidwengier** [comment]
Yep, sure thing.
