### ISSUE TITLE
Xliff-Tasks downloads 2.0.X prebuilt packages during source-build

### ISSUE THREAD

**Issue by lbussell** [dotnet/xliff-tasks#650]
The following packages are reported as source-build prebuilts for 7.0rc1:

- Microsoft.NETCore.App.2.0.3
- Microsoft.NETCore.DotNetAppHost.2.0.3
- Microsoft.NETCore.DotNetHostPolicy.2.0.3
- Microsoft.NETCore.DotNetHostResolver.2.0.3
- Microsoft.NETCore.Platforms.2.0.1

These packages should not be referenced or restored during the xliff-tasks build, as they are not available during source-build.

Steps to reproduce:

1. clone xliff-tasks
2. Run `./build.sh -c Release --restore --build --pack /p:ArcadeBuildFromSource=true -bl`
3. Run the following commands to see the restored prebuilts (the versions are slightly different than what we reported in the end-to-end source-build):
    `find artifacts/source-build/self/package-cache/ -iname *2.2.8*`
    `find artifacts/source-build/self/package-cache/ -iname *2.0.*.nupkg`

https://github.com/dotnet/installer/pull/14372 is a workaround, but including the prebuilts is only acceptable for RC1.

**Comment by MichaelSimons** [comment]
I am resolving this issue by adding the required reference packages in https://github.com/dotnet/source-build-reference-packages

**Comment by MichaelSimons** [comment]
@jonfortescue - I see you [recently upgraded](https://github.com/dotnet/xliff-tasks/commit/b3db63ddb6ab9e7e4c83b0980bb0f8556f3d248b#diff-104f1ffc6d9481db507346f7fc5ff004cce77334b46732cc918d05239685a8c2R32) the microsoft.netcore.app reference from 2.0.3 to 2.2.8.  2.2 is eol and therefore we should not be referencing it should we?

**Comment by jonfortescue** [comment]
Ah, you're definitely right, we should not be. I'm not sure how much work it would be to remove that dependency from the project.

**Comment by MichaelSimons** [comment]
This has a ripple effect on source-build so eliminating it would be nice but if that can't happen soon, we need to stick to a supported version.  As mentioned in the issue, this is a source of prebuilts that need to be eliminated for RC2.
