### ISSUE TITLE
Update projects to build net7.0 TFM

### ISSUE THREAD

**Issue by lbussell** [dotnet/xliff-tasks#651]
Source build requires projects to build with the current TFM and/or netstandard TFMs. xliff-tasks is targeting net6.0. Ideally the net6.0 reference would be updated to net7.0 to avoid pulling in prebuilts. If that is not possible, the TFM could be conditioned for source-build but ideally the regular build and source build would be identical.

@jonfortescue I see you just updated this repo to net6.0. Do you think it would be much more effort to update it to 7.0? In my experience it is usually pretty simple.

**Comment by jonfortescue** [comment]
I think it would be pretty simple to upgrade to net7.0, but currently we were targeting upgrading stuff to net6.0 from netcoreapp3.1 so we were on the next LTS. That effort is being tracked here: https://github.com/dotnet/arcade/issues/8998

If source build needs to have stuff on net7.0 then we must do what we must, I suppose.

cc/ @MattGal @garath for visibility/comment.

**Comment by garath** [comment]
@lbussell I'm curious, would it work if this targeted both net6.0 and net7.0?

**Comment by lbussell** [comment]
> @lbussell I'm curious, would it work if this targeted both net6.0 and net7.0?

No, it must target net7.0 only during source build (this can be a condition if absolutely necessary). 

Starting in net6.0 targeting packs contain roslyn-analyzers binaries. We wouldn't be able to target net6.0 during 7.0 source build unless we also source built a 6.0 version of roslyn-analyzers and all of its dependencies.
