### ISSUE TITLE
Migrate to dotnet/arcade

### ISSUE THREAD

**Issue by tmeschter** [dotnet/xliff-tasks#74]
We need to migrate the repo to build using the dotnet/arcade build tools.

Motivating factors:

- dotnet/arcade is a supported set of build tooling; adopting it will lower our maintenance costs for this repo and broaden the pool of people who can investigate infrastructure issues.
- xliff-tasks participates in the "source build" of .NET Core and this imposes certain requirements on it. Adopting Arcade will help us satisfy those requirements. 

Known work:

- [ ] Adopt the Arcade SDK.
- [ ] Update the signed build queue as appropriate.
- [ ] Validate the latest version of XliffTasks with a sample of dependent repos.
- [ ] Bug fixes to various repos related to previous item.

A note on the last couple of items: Since xliff-tasks does not currently participate in Arcade, other projects do not automatically get the latest version. In recent changes xliff-tasks has become more correct and demanding in its handling of .xlf files, and there is a good chance that other repos will need some fixes before they can adopt the latest version.

**Comment by garath** [comment]
This repository has moved to "maintenance only" mode, though it remains important to .NET efforts. We're closing stale issues. Please feel free to reopen if desired and we'll triage the issue.
