### ISSUE TITLE
XLiff TransformTemplates task collides with T4 generation

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/xliff-tasks#75]
The TextTemplating targets also have a task called "TransformTemplates". When you have a project that uses both XLiff and T4, it turns out that the XLiff task will be invoked by the TextTemplating targets, resulting in build errors that are incredibly difficult and painful to diagnose.

Ideally, this task should be renamed to something more unique.

cc @rainersigwald @nguerrera

**Comment by rainersigwald** [comment]
Renamed, or just referenced in both the UsingTask and its uses by a fully-qualified name.

**Comment by garath** [comment]
This repository has moved to "maintenance only" mode, though it remains important to .NET efforts. We're closing stale issues. Please feel free to reopen if desired and we'll triage the issue.
