### ISSUE TITLE
Error MSB4062: The "UpdateXlf" task could not be loaded from the assembly

### ISSUE THREAD

**Issue by mayadav1** [dotnet/xliff-tasks#795]
### Description

Facing issue while building linux version of performance test suite with local build.
Error MSB4062: The "UpdateXlf" task could not be loaded from the assembly /home/manoj/performance/artifacts/packages/microsoft.dotnet.xlifftasks/1.0.0-beta.23279.1/build/../tools/net8.0/Microsoft.DotNet.XliffTasks.dll. Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/home/manoj/performance/src/harness/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj]

Can somebody help me over it. your help will be appreciate.

### Reproduction Steps

 python scripts/benchmarks_ci.py --architecture x64 -c Release -f net6.0 --filter "System.Diagnostics.Perf_Process.GetProcesses*" --corerun "/home/manoj/runtime6/runtime/artifacts/bin/testhost/net6.0-Linux-Release-x64/shared/Microsoft.NETCore.App/6.0.18/corerun" --bdn-artifacts "/home/manoj/half6/

### Expected behavior

It should work.

### Actual behavior

Error MSB4062: The "UpdateXlf" task could not be loaded from the assembly /home/manoj/performance/artifacts/packages/microsoft.dotnet.xlifftasks/1.0.0-beta.23279.1/build/../tools/net8.0/Microsoft.DotNet.XliffTasks.dll. Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/home/manoj/performance/src/harness/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj]

**Comment by ViktorHofer** [comment]
You need an 8.0 SDK to run the 8.0 XliffTasks msbuild package.

**Comment by mayadav1** [comment]
@ViktorHofer , You are correct, I have one problem too, when I set dotnet_root it override the older versions and that also a cause of failures. I am extremely seeking a help.

**Comment by mayadav1** [comment]
@ViktorHofer , After installing all versions of SDK, I am still facing same error. I can run above command successfully with framework 8.0. But it doesn't run with 6.0 even though all version of sdk are set.

**Comment by ViktorHofer** [comment]
AFAIK that's by design. The 8.0 packages requires an 8.0 SDK (and shared framework) to be used. As the package changes rarely, the current recommendation is to use the 6.0 version of the package instead for a 6.0 SDK, 7.0 for a 7.0 SDK and 8.0 with an 8.0 SDK.

**Comment by mayadav1** [comment]
@ViktorHofer , Thanks for the suggestions : dotnet configurations are as  follows. 
 export DOTNET_ROOT=/home/manoj/dotnet/
manoj@vsdev-5900x-20:~$ export PATH=/home/manoj/dotnet/:$PATH
manoj@vsdev-5900x-20:~$ dotnet --list-sdks
6.0.408 [/home/manoj/dotnet/sdk]
7.0.302 [/home/manoj/dotnet/sdk]
8.0.100-preview.4.23260.5 [/home/manoj/dotnet/sdk]
manoj@vsdev-5900x-20:~$ dotnet --info
.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/manoj/dotnet/sdk/8.0.100-preview.4.23260.5/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.4.23259.5
  Architecture: x64
  Commit:       84a3d0e37e

.NET SDKs installed:
  6.0.408 [/home/manoj/dotnet/sdk]
  7.0.302 [/home/manoj/dotnet/sdk]
  8.0.100-preview.4.23260.5 [/home/manoj/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/home/manoj/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/home/manoj/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [/home/manoj/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/home/manoj/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/home/manoj/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [/home/manoj/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/manoj/dotnet/]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
I hope it is as you are expecting .

**Comment by missymessa** [comment]
Is there any additional work that needs to be done here?

**Comment by missymessa** [comment]
Doesn't sound like this is an issue anymore. Please re-open if this is not the case!
