### ISSUE TITLE
Detect when a resource is renamed

### ISSUE THREAD

**Issue by tmeschter** [dotnet/xliff-tasks#88]
If an existing resource is renamed in the source files (e.g., .resx, .vsct, etc.) at the .xlf level we treat this as the removal of an existing resource, plus the addition of a new resource. This means the target text is lost, even though the source text is likely unchanged.

We should try to be smarter about this. When adding a new resource as part of a .xlf file update we should check the set of deleted items and if we find one with an identical `source` and `notes` then re-use its `target` text.

Open question: should the `state` of the renamed resource be `translated`, `needs-review-translation`, or `new`? I'm leaning towards `needs-review-translation`.

**Comment by garath** [comment]
This repository has moved to "maintenance only" mode, though it remains important to .NET efforts. We're closing stale issues. Please feel free to reopen if desired and we'll triage the issue.
